Pin Name/Usage               : Location  : Dir.   : I/O Standard      : Voltage : I/O Bank  : User Assignment
-------------------------------------------------------------------------------------------------------------
ext_clk_25m                  : 23        : input  : 2.5 V             :         : 1         : Y              
ext_rst_n                    : 24        : input  : 2.5 V             :         : 2         : Y 

led[7]                       : 1         : output : 2.5 V             :         : 1         : Y              
led[6]                       : 2         : output : 2.5 V             :         : 1         : Y              
led[5]                       : 3         : output : 2.5 V             :         : 1         : Y     
led[4]                       : 7         : output : 2.5 V             :         : 1         : Y     
led[3]                       : 10        : output : 2.5 V             :         : 1         : Y              
led[2]                       : 11        : output : 2.5 V             :         : 1         : Y   
led[1]                       : 28        : output : 2.5 V             :         : 2         : Y       
led[0]                       : 30        : output : 2.5 V             :         : 2         : Y  
key_v[0]                     : 58        : input  : 2.5 V             :         : 4         : Y              
key_v[1]                     : 59        : input  : 2.5 V             :         : 4         : Y   
key_v[2]                     : 54        : input  : 2.5 V             :         : 4         : Y              
key_v[3]                     : 55        : input  : 2.5 V             :         : 4         : Y    
~ALTERA_DCLK~                : 12        : output : 2.5 V             :         : 1         : N

dtube_data[7]                : 3         : output : 2.5 V             :         : 1         : Y   
dtube_data[6]                : 10        : output : 2.5 V             :         : 1         : Y        
dtube_data[5]                : 28        : output : 2.5 V             :         : 2         : Y        
dtube_data[4]                : 1         : output : 2.5 V             :         : 1         : Y              
dtube_data[3]                : 2         : output : 2.5 V             :         : 1         : Y              
dtube_data[2]                : 7         : output : 2.5 V             :         : 1         : Y                           
dtube_data[1]                : 11        : output : 2.5 V             :         : 1         : Y                                                         
dtube_data[0]                : 30        : output : 2.5 V             :         : 2         : Y              
dtube_cs_n[3]                : 31        : output : 2.5 V             :         : 2         : Y              
dtube_cs_n[2]                : 32        : output : 2.5 V             :         : 2         : Y              
dtube_cs_n[1]                : 33        : output : 2.5 V             :         : 2         : Y              
dtube_cs_n[0]                : 34        : output : 2.5 V             :         : 2         : Y
~ALTERA_DCLK~                : 12        : output : 2.5 V             :         : 1         : N   

led[7]                       : 1         : output : 2.5 V             :         : 1         : Y  
led[6]                       : 2         : output : 2.5 V             :         : 1         : Y  
led[5]                       : 3         : output : 2.5 V             :         : 1         : Y              
led[4]                       : 7         : output : 2.5 V             :         : 1         : Y  
led[3]                       : 10        : output : 2.5 V             :         : 1         : Y  
led[2]                       : 11        : output : 2.5 V             :         : 1         : Y  
led[1]                       : 28        : output : 2.5 V             :         : 2         : Y  
led[0]                       : 30        : output : 2.5 V             :         : 2         : Y
sram_data[7]                 : 77        : bidir  : 2.5 V             :         : 5         : Y      
sram_data[6]                 : 76        : bidir  : 2.5 V             :         : 5         : Y   
sram_data[5]                 : 75        : bidir  : 2.5 V             :         : 5         : Y         
sram_data[4]                 : 74        : bidir  : 2.5 V             :         : 5         : Y
sram_data[3]                 : 73        : bidir  : 2.5 V             :         : 5         : Y
sram_data[2]                 : 80        : bidir  : 2.5 V             :         : 5         : Y  
sram_data[1]                 : 83        : bidir  : 2.5 V             :         : 5         : Y  
sram_data[0]                 : 84        : bidir  : 2.5 V             :         : 5         : Y
sram_addr[14]                : 110       : output : 2.5 V             :         : 7         : Y
sram_addr[13]                : 125       : output : 2.5 V             :         : 7         : Y
sram_addr[12]                : 111       : output : 2.5 V             :         : 7         : Y        
sram_addr[11]                : 120       : output : 2.5 V             :         : 7         : Y
sram_addr[10]                : 115       : output : 2.5 V             :         : 7         : Y      
sram_addr[9]                 : 121       : output : 2.5 V             :         : 7         : Y  
sram_addr[8]                 : 124       : output : 2.5 V             :         : 7         : Y         
sram_addr[7]                 : 112       : output : 2.5 V             :         : 7         : Y  
sram_addr[6]                 : 113       : output : 2.5 V             :         : 7         : Y
sram_addr[5]                 : 100       : output : 2.5 V             :         : 6         : Y  
sram_addr[4]                 : 99        : output : 2.5 V             :         : 6         : Y  
sram_addr[3]                 : 98        : output : 2.5 V             :         : 6         : Y      
sram_addr[2]                 : 87        : output : 2.5 V             :         : 5         : Y
sram_addr[1]                 : 86        : output : 2.5 V             :         : 5         : Y  
sram_addr[0]                 : 85        : output : 2.5 V             :         : 5         : Y    
sram_cs_n                    : 114       : output : 2.5 V             :         : 7         : Y           
sram_oe_n                    : 119       : output : 2.5 V             :         : 7         : Y  
sram_we_n                    : 126       : output : 2.5 V             :         : 7         : Y
ext_clk_25m                  : 23        : input  : 2.5 V             :         : 1         : Y  
ext_rst_n                    : 24        : input  : 2.5 V             :         : 2         : Y
altera_reserved_tdi          : 15        : input  : 2.5 V             :         : 1         : N  
altera_reserved_tck          : 16        : input  : 2.5 V             :         : 1         : N  
altera_reserved_tms          : 18        : input  : 2.5 V             :         : 1         : N  
altera_reserved_tdo          : 20        : output : 2.5 V             :         : 1         : N  
~ALTERA_DCLK~                : 12        : output : 2.5 V             :         : 1         : N 

lcd_light_en                 : 137       : output : 2.5 V             :         : 8         : Y   
lcd_clk                      : 67        : output : 2.5 V             :         : 4         : Y              
lcd_vsy                      : 68        : output : 2.5 V             :         : 4         : Y              
lcd_hsy                      : 69        : output : 2.5 V             :         : 4         : Y              
lcd_r[4]                     : 70        : output : 2.5 V             :         : 4         : Y              
lcd_r[3]                     : 71        : output : 2.5 V             :         : 4         : Y              
lcd_r[2]                     : 72        : output : 2.5 V             :         : 4         : Y              
lcd_r[1]                     : 101       : output : 2.5 V             :         : 6         : Y              
lcd_r[0]                     : 103       : output : 2.5 V             :         : 6         : Y              
lcd_g[5]                     : 104       : output : 2.5 V             :         : 6         : Y              
lcd_g[4]                     : 105       : output : 2.5 V             :         : 6         : Y
lcd_g[3]                     : 127       : output : 2.5 V             :         : 7         : Y                          
lcd_g[2]                     : 106       : output : 2.5 V             :         : 6         : Y              
lcd_g[1]                     : 129       : output : 2.5 V             :         : 8         : Y       
lcd_g[0]                     : 128       : output : 2.5 V             :         : 8         : Y              
lcd_b[4]                     : 133       : output : 2.5 V             :         : 8         : Y
lcd_b[3]                     : 132       : output : 2.5 V             :         : 8         : Y                            
lcd_b[2]                     : 136       : output : 2.5 V             :         : 8         : Y
lcd_b[1]                     : 135       : output : 2.5 V             :         : 8         : Y                                   
lcd_b[0]                     : 138       : output : 2.5 V             :         : 8         : Y                      
ext_clk_25m                  : 23        : input  : 2.5 V             :         : 1         : Y              
ext_rst_n                    : 24        : input  : 2.5 V             :         : 2         : Y   
~ALTERA_DCLK~                : 12        : output : 2.5 V             :         : 1         : N   
             
